services:
  nginx:
    image: nginx:1.27.2
    container_name: ${APP_NAME}-nginx
    command: /bin/sh -c "export APP_NAME=${APP_NAME} && envsubst '\$\{APP_NAME\}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./cicd/local/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./public:/var/www/html/public
    depends_on:
      - php-fpm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.localhost`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=web"
      - "traefik.http.services.${APP_NAME}-svc.loadbalancer.server.port=80"
    networks:
      - dev-net

  php-fpm:
    image: php:8.3-fpm-alpine
    container_name: ${APP_NAME}-php-fpm
    volumes:
      - .:/var/www/html
    labels:
      - "traefik.enable=false"
    networks:
      - dev-net

networks:
  dev-net:
    external: true
