services:
  traefik:
    image: traefik:v3.3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.network=dev-net"
      - "--entrypoints.web.address=:80"
    ports:
      - "${TRAEFIK_WEB_PORT}:80"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=false"
    networks:
      - dev-net

networks:
  dev-net:
    external: true
