services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=false"
    networks:
      - dev-net
networks:
  dev-net:
    external: true
